// SPDX-License-Identifier: Apache-2.0
//
// Node-side wallet, and the WalletProvider / MidnightProvider pair that lets
// midnight-js balance, sign, and submit transactions with it.
//
// This is NOT the browser path. lib/midnight/wallet.ts talks to Lace through
// the DApp connector and never sees a secret key; this module holds real
// signing material derived from a seed and is intended for deploy scripts and
// CI provisioning only. Keep it out of any client bundle.
//
// A Midnight wallet is three sub-wallets behind one facade:
//   shielded   — Zswap notes, the private balance
//   unshielded — NIGHT UTxOs, the public balance and the address you fund
//   dust       — DUST, which pays fees and is generated by registered NIGHT
//
// All three must be synced before a transaction can be balanced.

import { readFileSync } from "node:fs";

// ZswapSecretKeys and DustSecretKey are VALUE imports: the secret keys must be
// constructed with their .fromSeed() factories. Importing them via `import
// type` compiles but leaves nothing to call at runtime. They must also come
// from this exact specifier — the same one testkit-js uses — because these are
// WASM-backed classes whose instances are checked with _assertClass; a second
// copy of ledger-v8 would make every instance "not an instance of".
import {
  DustSecretKey,
  ZswapSecretKeys,
} from "@midnight-ntwrk/midnight-js-protocol/ledger";
import type {
  CoinPublicKey,
  EncPublicKey,
  FinalizedTransaction,
} from "@midnight-ntwrk/midnight-js-protocol/ledger";
import type {
  MidnightProvider,
  UnboundTransaction,
  WalletProvider,
} from "@midnight-ntwrk/midnight-js-types";
import { ttlOneHour } from "@midnight-ntwrk/midnight-js-utils";
import { FluentWalletBuilder } from "@midnight-ntwrk/testkit-js";
import {
  MidnightBech32m,
  UnshieldedAddress,
} from "@midnight-ntwrk/wallet-sdk-address-format";

import type { WalletFacade } from "@midnight-ntwrk/wallet-sdk-facade";

import type { NetworkEndpoints } from "../network";

/**
 * Implements both halves of the transaction path that midnight-js expects.
 *
 * WalletProvider answers "who am I and how do I pay for this" (the public keys
 * plus balancing); MidnightProvider answers "put it on chain" (submission).
 * They are separate interfaces but one object satisfies both, which is why the
 * providers record below lists this instance twice.
 */
export class NodeWalletProvider implements WalletProvider, MidnightProvider {
  constructor(
    readonly wallet: WalletFacade,
    private readonly zswapSecretKeys: ZswapSecretKeys,
    private readonly dustSecretKey: DustSecretKey,
  ) {}

  getCoinPublicKey(): CoinPublicKey {
    return this.zswapSecretKeys.coinPublicKey;
  }

  getEncryptionPublicKey(): EncPublicKey {
    return this.zswapSecretKeys.encryptionPublicKey;
  }

  /**
   * Funds an unbound transaction and finalizes it.
   *
   * Balancing is what attaches inputs to cover the fee, so this is the step
   * that fails when DUST has not been registered — the wallet holds NIGHT but
   * has nothing it is allowed to spend on fees.
   */
  async balanceTx(
    tx: UnboundTransaction,
    ttl: Date = ttlOneHour(),
  ): Promise<FinalizedTransaction> {
    const recipe = await this.wallet.balanceUnboundTransaction(
      tx,
      {
        shieldedSecretKeys: this.zswapSecretKeys,
        dustSecretKey: this.dustSecretKey,
      },
      { ttl },
    );
    return this.wallet.finalizeRecipe(recipe);
  }

  submitTx(tx: FinalizedTransaction): Promise<string> {
    return this.wallet.submitTransaction(tx);
  }

  stop(): Promise<void> {
    return this.wallet.stop();
  }
}

export type WalletSummary = {
  /** Bech32m unshielded address — this is what you paste into the faucet. */
  readonly address: string;
  /** Unshielded balances by raw token type. */
  readonly balances: Record<string, bigint>;
  /** Spendable DUST. Zero means fees cannot be paid yet. */
  readonly dust: bigint;
};

/**
 * Builds a wallet from a seed and waits for it to finish syncing.
 *
 * FluentWalletBuilder is the same helper Midnight's own bboard tutorial uses.
 * It exists because WalletFacade.init() takes a configuration assembled from
 * five separate SDK packages; the builder fills all of that in from one
 * endpoint record. The tradeoff is a dependency on @midnight-ntwrk/testkit-js,
 * which is versioned in lockstep with midnight-js (both 4.1.1).
 *
 * Sync is not instant. On preprod the first sync of a fresh wallet routinely
 * takes a few minutes, and balanceTx will fail with a confusing error if you
 * skip it, so this always waits.
 */
export async function buildWallet(
  env: NetworkEndpoints,
  seedHex: string,
): Promise<{ provider: NodeWalletProvider; summary: WalletSummary }> {
  const built = await FluentWalletBuilder.forEnvironment({
    walletNetworkId: env.networkId,
    networkId: env.networkId,
    indexer: env.indexer,
    indexerWS: env.indexerWS,
    node: env.node,
    nodeWS: env.nodeWS,
    proofServer: env.proofServer,
    faucet: env.faucet,
  } as never)
    .withSeed(seedHex)
    .buildWithoutStarting();

  const { wallet, seeds } = built;

  // buildWithoutStarting() hands back WalletSeeds, whose .shielded/.unshielded/
  // .dust are RAW derived key bytes (Uint8Array) — there is no .keys/.key
  // sub-object. Reading those undefined properties and passing them to start()
  // fails much later and very confusingly, during the first sync update, as
  // "expected instance of DustSecretKey" thrown from inside the ledger WASM.
  // This mirrors testkit-js's own WalletFactory.startWalletFacade().
  const zswapSecretKeys = ZswapSecretKeys.fromSeed(seeds.shielded);
  const dustSecretKey = DustSecretKey.fromSeed(seeds.dust);

  await wallet.start(zswapSecretKeys, dustSecretKey);

  const state = await wallet.waitForSyncedState();

  const provider = new NodeWalletProvider(
    wallet,
    zswapSecretKeys,
    dustSecretKey,
  );

  return {
    provider,
    summary: {
      address: String(state.unshielded.address),
      balances: state.unshielded.balances,
      // DUST accrues continuously from registered NIGHT, so the balance is a
      // function of time, not a stored field. Must be called with a clock
      // reading; there is no `balances` property on DustWalletState.
      dust: state.dust.balance(new Date()),
    },
  };
}

/**
 * Returns the deployer's unshielded (NIGHT) address WITHOUT syncing.
 *
 * This exists because a full sync is currently unusable on preprod: the wallet
 * SDK grows the heap without bound while replaying chain history
 * (midnightntwrk/midnight-wallet#704, still open), and there is no supported
 * checkpoint / start-from-block option to skip it. Raising
 * --max-old-space-size only moves the OOM later.
 *
 * The address, though, never needed the chain. It is derived purely from the
 * unshielded keystore, which buildWithoutStarting() hands back already seeded
 * from the key material. So the address you fund at the faucet can be printed
 * immediately, even while sync is broken.
 */
export async function deployerAddress(
  env: NetworkEndpoints,
  seedHex: string,
): Promise<string> {
  const built = await FluentWalletBuilder.forEnvironment({
    walletNetworkId: env.networkId,
    networkId: env.networkId,
    indexer: env.indexer,
    indexerWS: env.indexerWS,
    node: env.node,
    nodeWS: env.nodeWS,
    proofServer: env.proofServer,
    faucet: env.faucet,
  } as never)
    .withSeed(seedHex)
    .buildWithoutStarting();

  // keystore.getAddress() returns a UserAddress — raw 32-byte hex. The faucet
  // and every explorer want the bech32m form (mn_addr_...), so encode it.
  const hex = String(built.keystore.getAddress());
  const address = MidnightBech32m.encode(
    env.networkId,
    new UnshieldedAddress(Buffer.from(hex, "hex")),
  ).toString();

  // Never started, so nothing to stop; the keystore is pure key material.
  return address;
}

/**
 * Reads the deployer seed.
 *
 * Prefers MIDNIGHT_WALLET_SEED_FILE over MIDNIGHT_WALLET_SEED so the secret can
 * live in a file that is never expanded into the process listing or a shell
 * history. Neither is ever logged.
 */
export function readSeed(): string {
  const file = process.env.MIDNIGHT_WALLET_SEED_FILE;
  if (file) return readFileSync(file, "utf8").trim();

  const inline = process.env.MIDNIGHT_WALLET_SEED;
  if (inline) return inline.trim();

  throw new Error(
    "No deployer seed. Set MIDNIGHT_WALLET_SEED_FILE (preferred) or " +
      "MIDNIGHT_WALLET_SEED to a 128-character hex seed.\n" +
      "Generate one with: node scripts/new-deploy-wallet.mjs\n" +
      "It must be 128 hex chars (64 bytes) — the standard BIP-39 " +
      "mnemonicToSeed output. A 64-char seed is accepted by the SDK but has " +
      "no mnemonic and can never be imported into Lace.",
  );
}
